spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/fitness_user_db
    username: fitness_user
    password: fitness_user_pwd

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8484

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8383/eureka/